/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import pl2_project.Admin;
import pl2_project.Employee;
import static pl2_project.Employee.employee;
import pl2_project.FileManger;
import pl2_project.ExClass;

/**
 *
 * @author y_awn
 */
public class Adminfrm extends javax.swing.JFrame implements  Serializable {

    /**
     * Creates new form Adminfrm
     */
    
    public Adminfrm() {
        initComponents();
        addRowsTojTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Addbtn = new javax.swing.JButton();
        Modifybtn = new javax.swing.JButton();
        Listbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Addpnl = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtQuali = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtUN = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        txtRePass = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        DOB = new javax.swing.JTextField();
        DOJ = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        Modifypnl = new javax.swing.JPanel();
        MAge = new javax.swing.JTextField();
        Searchbtn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Mphone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        MAddress = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        MName = new javax.swing.JTextField();
        Msalary = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        MQuali = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        MUS = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        MDOB = new javax.swing.JTextField();
        MDOJ = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        MID = new javax.swing.JTextField();
        MPass = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        Listpnl = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(0, 18, 50));

        jPanel4.setBackground(new java.awt.Color(0, 18, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\citi-icon.png")); // NOI18N

        Addbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\+.png")); // NOI18N
        Addbtn.setText("Add Employee");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });

        Modifybtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\+-.png")); // NOI18N
        Modifybtn.setText("Modify Employee");
        Modifybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifybtnActionPerformed(evt);
            }
        });

        Listbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\table.png")); // NOI18N
        Listbtn.setText("List Employees");
        Listbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListbtnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\user-add-icon.png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\Update.png")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\checklist-icon.png")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 66, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Listbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Modifybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(Addbtn)
                .addGap(48, 48, 48)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Modifybtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Listbtn)
                .addGap(102, 102, 102))
        );

        jPanel5.setBackground(new java.awt.Color(32, 47, 90));
        jPanel5.setLayout(new java.awt.CardLayout());

        Addpnl.setBackground(new java.awt.Color(32, 47, 90));
        Addpnl.setLayout(null);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date Of Birth:");
        Addpnl.add(jLabel9);
        jLabel9.setBounds(10, 300, 77, 14);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Phone:");
        Addpnl.add(jLabel10);
        jLabel10.setBounds(10, 420, 50, 14);

        txtAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addpnl.add(txtAge);
        txtAge.setBounds(170, 360, 215, 30);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address:");
        Addpnl.add(jLabel11);
        jLabel11.setBounds(10, 460, 50, 14);

        txtPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addpnl.add(txtPhone);
        txtPhone.setBounds(170, 400, 215, 30);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Salary:");
        Addpnl.add(jLabel6);
        jLabel6.setBounds(10, 500, 50, 14);

        txtAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        Addpnl.add(txtAddress);
        txtAddress.setBounds(170, 440, 215, 30);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Qualifications:");
        Addpnl.add(jLabel12);
        jLabel12.setBounds(10, 530, 77, 14);

        txtSalary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addpnl.add(txtSalary);
        txtSalary.setBounds(170, 480, 215, 30);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Gender:");
        Addpnl.add(jLabel13);
        jLabel13.setBounds(10, 560, 46, 14);

        txtQuali.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addpnl.add(txtQuali);
        txtQuali.setBounds(170, 520, 215, 30);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Date Of Join:");
        Addpnl.add(jLabel14);
        jLabel14.setBounds(10, 340, 77, 14);

        Male.setBackground(new java.awt.Color(0, 18, 50));
        buttonGroup1.add(Male);
        Male.setForeground(new java.awt.Color(255, 255, 255));
        Male.setText("Male");
        Addpnl.add(Male);
        Male.setBounds(170, 560, 70, 23);

        Female.setBackground(new java.awt.Color(0, 18, 50));
        buttonGroup1.add(Female);
        Female.setForeground(new java.awt.Color(255, 255, 255));
        Female.setText("Female");
        Addpnl.add(Female);
        Female.setBounds(300, 560, 80, 23);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Age:");
        Addpnl.add(jLabel15);
        jLabel15.setBounds(10, 380, 49, 14);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("UserName:");
        Addpnl.add(jLabel16);
        jLabel16.setBounds(10, 90, 64, 14);

        txtUN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addpnl.add(txtUN);
        txtUN.setBounds(170, 80, 215, 30);

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Password:");
        Addpnl.add(jLabel17);
        jLabel17.setBounds(10, 140, 64, 14);

        txtPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addpnl.add(txtPass);
        txtPass.setBounds(170, 120, 215, 30);

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Re-Password");
        Addpnl.add(jLabel18);
        jLabel18.setBounds(10, 180, 77, 14);

        txtRePass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addpnl.add(txtRePass);
        txtRePass.setBounds(170, 160, 215, 30);

        jButton2.setBackground(new java.awt.Color(0, 18, 50));
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Addpnl.add(jButton2);
        jButton2.setBounds(200, 630, 149, 30);

        jButton4.setBackground(new java.awt.Color(0, 18, 50));
        jButton4.setForeground(new java.awt.Color(0, 102, 204));
        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Addpnl.add(jButton4);
        jButton4.setBounds(200, 590, 149, 30);

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\Shutdown_42px.png")); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        Addpnl.add(jLabel19);
        jLabel19.setBounds(0, 0, 44, 42);

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Name:");
        Addpnl.add(jLabel20);
        jLabel20.setBounds(10, 220, 64, 14);

        txtID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addpnl.add(txtID);
        txtID.setBounds(170, 240, 215, 30);

        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        Addpnl.add(jLabel22);
        jLabel22.setBounds(490, 0, 44, 0);

        DOB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addpnl.add(DOB);
        DOB.setBounds(170, 280, 215, 30);

        DOJ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addpnl.add(DOJ);
        DOJ.setBounds(170, 320, 215, 30);

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Name:");
        Addpnl.add(jLabel34);
        jLabel34.setBounds(10, 220, 64, 14);

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Name:");
        Addpnl.add(jLabel35);
        jLabel35.setBounds(10, 220, 64, 14);

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("ID:");
        Addpnl.add(jLabel8);
        jLabel8.setBounds(10, 260, 15, 14);

        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addpnl.add(txtName);
        txtName.setBounds(170, 200, 215, 30);

        jLabel43.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\AppData\\Local\\Temp\\Close Window_48px.png")); // NOI18N
        jLabel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel43MouseClicked(evt);
            }
        });
        Addpnl.add(jLabel43);
        jLabel43.setBounds(480, 0, 50, 40);

        jPanel5.add(Addpnl, "card2");

        Modifypnl.setBackground(new java.awt.Color(32, 47, 90));
        Modifypnl.setLayout(null);

        MAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(MAge);
        MAge.setBounds(160, 350, 220, 30);

        Searchbtn.setBackground(new java.awt.Color(0, 18, 50));
        Searchbtn.setForeground(new java.awt.Color(0, 102, 204));
        Searchbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\AppData\\Local\\Temp\\Search_20px.png")); // NOI18N
        Searchbtn.setText("Serach");
        Searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbtnActionPerformed(evt);
            }
        });
        Modifypnl.add(Searchbtn);
        Searchbtn.setBounds(230, 60, 99, 20);

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Address:");
        Modifypnl.add(jLabel21);
        jLabel21.setBounds(10, 440, 60, 14);

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\Shutdown_42px.png")); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        Modifypnl.add(jLabel23);
        jLabel23.setBounds(10, 0, 44, 42);

        Mphone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(Mphone);
        Mphone.setBounds(160, 390, 220, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Salary:");
        Modifypnl.add(jLabel7);
        jLabel7.setBounds(10, 480, 60, 14);

        MAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(MAddress);
        MAddress.setBounds(160, 430, 220, 30);

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Name:");
        Modifypnl.add(jLabel24);
        jLabel24.setBounds(10, 200, 70, 14);

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Qualifications:");
        Modifypnl.add(jLabel25);
        jLabel25.setBounds(10, 520, 80, 14);

        MName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(MName);
        MName.setBounds(160, 190, 220, 30);

        Msalary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(Msalary);
        Msalary.setBounds(160, 470, 220, 30);

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Gender:");
        Modifypnl.add(jLabel26);
        jLabel26.setBounds(10, 560, 50, 14);

        MQuali.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MQuali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MQualiActionPerformed(evt);
            }
        });
        Modifypnl.add(MQuali);
        MQuali.setBounds(160, 510, 220, 30);

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Date Of Join:");
        Modifypnl.add(jLabel27);
        jLabel27.setBounds(10, 320, 80, 14);

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Age:");
        Modifypnl.add(jLabel28);
        jLabel28.setBounds(10, 360, 50, 14);

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("UserName:");
        Modifypnl.add(jLabel29);
        jLabel29.setBounds(10, 120, 70, 14);

        MUS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(MUS);
        MUS.setBounds(160, 110, 220, 30);

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Password:");
        Modifypnl.add(jLabel30);
        jLabel30.setBounds(10, 160, 70, 14);

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("ID:");
        Modifypnl.add(jLabel31);
        jLabel31.setBounds(10, 240, 80, 14);

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Date Of Birth:");
        Modifypnl.add(jLabel32);
        jLabel32.setBounds(10, 280, 80, 14);

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Phone:");
        Modifypnl.add(jLabel33);
        jLabel33.setBounds(10, 400, 60, 14);

        txtSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        Modifypnl.add(txtSearch);
        txtSearch.setBounds(10, 60, 200, 20);

        btnUpdate.setBackground(new java.awt.Color(0, 18, 50));
        btnUpdate.setForeground(new java.awt.Color(0, 204, 51));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        Modifypnl.add(btnUpdate);
        btnUpdate.setBounds(210, 590, 99, 23);

        btnDelete.setBackground(new java.awt.Color(0, 18, 50));
        btnDelete.setForeground(new java.awt.Color(255, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        Modifypnl.add(btnDelete);
        btnDelete.setBounds(210, 630, 99, 23);

        MDOB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(MDOB);
        MDOB.setBounds(160, 270, 220, 30);

        MDOJ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(MDOJ);
        MDOJ.setBounds(160, 310, 220, 30);

        txtGender.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(txtGender);
        txtGender.setBounds(160, 550, 220, 30);

        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        Modifypnl.add(jLabel36);
        jLabel36.setBounds(490, 0, 44, 0);

        MID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(MID);
        MID.setBounds(160, 230, 220, 30);

        MPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(MPass);
        MPass.setBounds(160, 150, 220, 30);
        Modifypnl.add(jSeparator1);
        jSeparator1.setBounds(10, 80, 200, 2);

        jLabel42.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\AppData\\Local\\Temp\\Close Window_48px.png")); // NOI18N
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel42MouseClicked(evt);
            }
        });
        Modifypnl.add(jLabel42);
        jLabel42.setBounds(480, 0, 50, 40);

        jPanel5.add(Modifypnl, "card2");

        Listpnl.setBackground(new java.awt.Color(32, 47, 90));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\Todo List_20px.png")); // NOI18N
        jButton1.setText("List All Employees");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\Shutdown_42px.png")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel41.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\AppData\\Local\\Temp\\Close Window_48px.png")); // NOI18N
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Password", "Name", "ID", "Date Of Birth", "Date Of Join", "Age", "Phone", "Address", "Salary", "Qulaifications", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout ListpnlLayout = new javax.swing.GroupLayout(Listpnl);
        Listpnl.setLayout(ListpnlLayout);
        ListpnlLayout.setHorizontalGroup(
            ListpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListpnlLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(ListpnlLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(ListpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );
        ListpnlLayout.setVerticalGroup(
            ListpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListpnlLayout.createSequentialGroup()
                .addGroup(ListpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );

        jPanel5.add(Listpnl, "card2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(729, 673));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void addRowsTojTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object rowData[] = new Object[12];

        Employee e = new Employee();
        ArrayList<Employee> employee = new ArrayList<Employee>();

        employee = e.listEmployee();
                    
        for (Employee x : employee) {
            rowData[0] = x.getuserName();
            rowData[1] = x.getpassword();
            rowData[2] = x.getName();
            rowData[3] = x.getId();
            rowData[4] = x.getDateOfBirth();
            rowData[5] = x.getdoj();
            rowData[6] = x.getage();
            rowData[7] = x.getphone();
            rowData[8] = x.getaddress();
            rowData[9] = x.getsalary();
            rowData[10] = x.getqulaifications();
            rowData[11] = x.getGender();
            
            model.addRow(rowData);
        }     
    }
    
    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        // TODO add your handling code here:
     jPanel5.removeAll();
     jPanel5.repaint();
     jPanel5.revalidate();
     
     jPanel5.add(Addpnl);
     jPanel5.repaint();
     jPanel5.revalidate();
     
    }//GEN-LAST:event_AddbtnActionPerformed

    private void ModifybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifybtnActionPerformed
        // TODO add your handling code here:
      jPanel5.removeAll();
     jPanel5.repaint();
     jPanel5.revalidate();
     
     jPanel5.add(Modifypnl);
     jPanel5.repaint();
     jPanel5.revalidate();
    }//GEN-LAST:event_ModifybtnActionPerformed

    private void ListbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListbtnActionPerformed
        // TODO add your handling code here:
         jPanel5.removeAll();
     jPanel5.repaint();
     jPanel5.revalidate();
     
     jPanel5.add(Listpnl);
     jPanel5.repaint();
     jPanel5.revalidate();
    }//GEN-LAST:event_ListbtnActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to logout?","Logout",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            dispose();
            Loginfrm l=new Loginfrm();
            l.setVisible(true);
        } 
        
    }//GEN-LAST:event_jLabel5MouseClicked
 public void ResetA(){
       txtUN.setText("");
        txtPass.setText("");
        txtRePass.setText("");
        txtName.setText("");
        txtID.setText("");
        DOB.setText("");
        DOJ.setText("");
        txtAge.setText("");
        txtPhone.setText("");
        txtAddress.setText("");
        txtSalary.setText("");
        txtQuali.setText("");
        buttonGroup1.clearSelection();
 
 }
 public void ResetM(){
       MUS.setText("");
        MPass.setText("");
        MName.setText("");
        MID.setText("");
        MDOB.setText("");
        MDOJ.setText("");
        MAge.setText("");
        Mphone.setText("");
        MAddress.setText("");
        Msalary.setText("");
        MQuali.setText("");
        txtGender.setText("");
 }

 
 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ResetA();
    }//GEN-LAST:event_jButton2ActionPerformed
 FileManger FM=new FileManger();
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    Employee w=new Employee();
    int ID=Integer.parseInt(txtID.getText());
    int index=w.getEmployeeIndex(ID);
    if(index==-1){
        if (txtPass.getText().equals(txtRePass.getText())){
    String gender = null;
    if(Male.isSelected()){
    gender="Male";
    }
    else if(Female.isSelected()){
    gender="Female";
    }
        int i=0;
        int k;
      ExClass n=new ExClass();
      k=n.ValidateUS(txtUN.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "UserName in not validated");}
      k=n.ValidatePassword(txtPass.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Password in not validated");}
      k=n.ValidtaeName(txtName.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Name in not validated");}
      k=n.ValidateNumber(txtID.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "ID in not validated");}
     
      k=n.ValidateNumber(txtAge.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Age in not validated");}
      k=n.ValidateNumber(txtPhone.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Phone in not validated");}
      k=n.ValidateNumber(txtSalary.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Salary in not validated");}
      if(i==7){
        Admin admin = new Admin();
        admin.addNewEmployee(txtUN.getText(), txtPass.getText() ,txtName.getText(),Integer.parseInt(txtID.getText()) ,DOB.getText(), DOJ.getText() ,Integer.parseInt(txtAge.getText()) ,Long.parseLong(txtPhone.getText()) ,txtAddress.getText() ,Double.parseDouble(txtSalary.getText()) ,txtQuali.getText(), gender);
        JOptionPane.showMessageDialog(null,"Done!!");
       ResetA();}
      else{
          JOptionPane.showMessageDialog(null,"2");
      }
    }
    else{
    JOptionPane.showMessageDialog(null,"The Password and Re-password are not matching");
    }}
    else{
    JOptionPane.showMessageDialog(null,"the ID is already exist");
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
      int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to logout?","Logout",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            dispose();
             Loginfrm l=new Loginfrm();
            l.setVisible(true);
        }
         
       
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to Exit?","Exit",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
         
       
    }//GEN-LAST:event_jLabel22MouseClicked
    
    private void SearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbtnActionPerformed
if (!txtSearch.getText().equals("")) {
           String Gender=null;
           Employee x = new Employee();
           x.LoadFromFile();
          int id= Integer.parseInt(txtSearch.getText());
          int index= x.getEmployeeIndex(id);
          if(index!=-1){
              MUS.setText(employee.get(index).getuserName());
              MPass.setText(employee.get(index).getpassword());
              MName.setText(employee.get(index).getName());
              MID.setText(String.valueOf(employee.get(index).getId()));
              MDOB.setText(employee.get(index).getDateOfBirth());
              MDOJ.setText(employee.get(index).getdoj());
              MAge.setText(String.valueOf(employee.get(index).getage()));
              Mphone.setText(String.valueOf(employee.get(index).getphone()));
              MAddress.setText(employee.get(index).getaddress());
              Msalary.setText(String.valueOf(employee.get(index).getsalary()));
              MQuali.setText(employee.get(index).getqulaifications());
             txtGender.setText(employee.get(index).getGender());
              
              
          }
    
            
            else {
             JOptionPane.showMessageDialog(null, "Not Found ...!");
            }
        } else {
           JOptionPane.showMessageDialog(null, "Missing required Fields ... !  Please, Search By ID before submit ...!");
        }
        
         
    }//GEN-LAST:event_SearchbtnActionPerformed

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to logout?","Logout",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            dispose();
            Loginfrm l=new Loginfrm();
            l.setVisible(true);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23MouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void MQualiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MQualiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MQualiActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
          int i=0;
        int k;
      ExClass n=new ExClass();
      k=n.ValidateUS(MUS.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "UserName in not validated");}
      k=n.ValidatePassword(MPass.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Password in not validated");}
      k=n.ValidtaeName(MName.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Name in not validated");}
      k=n.ValidateNumber(MID.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "ID in not validated");}
     
      k=n.ValidateNumber(MAge.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Age in not validated");}
      k=n.ValidateNumber(Mphone.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Phone in not validated");}
      k=n.ValidateNumber(Msalary.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Salary in not validated");}
if(i==7){
    
        Employee x= new Employee();
        x.SetUserName(MUS.getText());
        x.SetPassword(MPass.getText());
        x.SetName(MName.getText());
        x.SetId(Integer.parseInt(MID.getText()));
        x.SetDateOfBirth(MDOB.getText());
        x.Setdoj(MDOJ.getText());
        x.SetAge(Integer.parseInt(MAge.getText()));
        x.SetPhone(Long.parseLong(Mphone.getText()));
        x.SetAddress(MAddress.getText());
        x.Setsalary(Double.parseDouble(Msalary.getText()));
        x.Setqulaifications(MQuali.getText());
        x.SetGender(txtGender.getText());
        if(x.updateEmployee()){
        JOptionPane.showMessageDialog(null, "Updated Successfully....!!!!");
        ResetM();
        txtSearch.setText("");
        }
        else{
        JOptionPane.showMessageDialog(null, "Faild To Update!!!");
        }
}
else{
JOptionPane.showMessageDialog(null,"Please insert coreect data");
}
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       if (!txtSearch.getText().equals("")) {
       Employee e=new Employee();
       if(e.deleteEmployee(Integer.parseInt(txtSearch.getText()))){
       JOptionPane.showMessageDialog(null, "Deleted Done!!");
      ResetM();
       }
       else{
       JOptionPane.showMessageDialog(null,"Failed to Delete");
       }
       
       }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
 int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to Exit?","Exit",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
        int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to Exit?","Exit",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel41MouseClicked

    private void jLabel42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseClicked
        int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to Exit?","Exit",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel42MouseClicked

    private void jLabel43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseClicked
        int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to Exit?","Exit",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel43MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JPanel Addpnl;
    private javax.swing.JTextField DOB;
    private javax.swing.JTextField DOJ;
    private javax.swing.JRadioButton Female;
    private javax.swing.JButton Listbtn;
    private javax.swing.JPanel Listpnl;
    private javax.swing.JTextField MAddress;
    private javax.swing.JTextField MAge;
    private javax.swing.JTextField MDOB;
    private javax.swing.JTextField MDOJ;
    private javax.swing.JTextField MID;
    private javax.swing.JTextField MName;
    private javax.swing.JTextField MPass;
    private javax.swing.JTextField MQuali;
    private javax.swing.JTextField MUS;
    private javax.swing.JRadioButton Male;
    private javax.swing.JButton Modifybtn;
    private javax.swing.JPanel Modifypnl;
    private javax.swing.JTextField Mphone;
    private javax.swing.JTextField Msalary;
    private javax.swing.JButton Searchbtn;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtQuali;
    private javax.swing.JPasswordField txtRePass;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUN;
    // End of variables declaration//GEN-END:variables
}
