/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.DoubleStream;
import java.util.stream.IntStream;
import javax.imageio.ImageIO;
import javax.mail.MessagingException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.RefineryUtilities;
import pl2_project.Admin;
import pl2_project.BarChart;
import pl2_project.Customer;
import static pl2_project.Customer.customer;
import pl2_project.Email;
import pl2_project.Employee;
import static pl2_project.Employee.employee;
import pl2_project.ExClass;
import pl2_project.Transactions;
import static pl2_project.Transactions.transactions;

/**
 *
 * @author y_awn
 */
public class Employeefrm extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    public Employeefrm() {
        initComponents();
        addRowsTojTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Addbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Modifybtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Listbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Transactions = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Listbtn2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Addpnl = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtMS = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtAC = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        DOB = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txtFN = new javax.swing.JTextField();
        txtMN = new javax.swing.JTextField();
        lbName = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();
        txtpic = new javax.swing.JTextField();
        Modifypnl = new javax.swing.JPanel();
        MAge = new javax.swing.JTextField();
        Searchbtn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Mphone = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        MAddress = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        MID = new javax.swing.JTextField();
        MBalance = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        MMS = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        MMN = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        MDOB = new javax.swing.JTextField();
        MAC = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        MFN = new javax.swing.JTextField();
        MName = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        MEmail = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        Listpnl = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Transactionpnl = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        txtMACN = new javax.swing.JTextField();
        h = new javax.swing.JTextField();
        txtbalance = new javax.swing.JTextField();
        txtM = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        Withdraw = new javax.swing.JRadioButton();
        Deposite = new javax.swing.JRadioButton();
        Transfeermoney = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        btnSeacrh2 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtCName = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        txtTN = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        yassen = new javax.swing.JLabel();
        txtcc = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        txtsub = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        txtCBS = new javax.swing.JButton();
        txtb = new javax.swing.JLabel();
        txtReset = new javax.swing.JButton();
        Reportpnl = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        CBSpnl = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtFB = new javax.swing.JLabel();
        txtW = new javax.swing.JLabel();
        txtD = new javax.swing.JLabel();
        txtT = new javax.swing.JLabel();
        txtFinalB = new javax.swing.JLabel();
        txtac = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(32, 47, 90));

        jPanel2.setBackground(new java.awt.Color(0, 18, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\citi-icon.png")); // NOI18N

        Addbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\+.png")); // NOI18N
        Addbtn.setText("Add Customer");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\user-add-icon.png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\Update.png")); // NOI18N

        Modifybtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\+-.png")); // NOI18N
        Modifybtn.setText("Modify Customer");
        Modifybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifybtnActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\checklist-icon.png")); // NOI18N

        Listbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\table.png")); // NOI18N
        Listbtn.setText("List Customer");
        Listbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListbtnActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\Banknotes_60px.png")); // NOI18N

        Transactions.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\AppData\\Local\\Temp\\US Dollar_20px.png")); // NOI18N
        Transactions.setText("Transactions");
        Transactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionsActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\AppData\\Local\\Temp\\Bullish_48px.png")); // NOI18N

        Listbtn2.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\AppData\\Local\\Temp\\Bar Chart_20px.png")); // NOI18N
        Listbtn2.setText("Report");
        Listbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listbtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Addbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Modifybtn, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(Listbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Transactions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Listbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(74, 74, 74))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Addbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Modifybtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Listbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Transactions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Listbtn2)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new java.awt.CardLayout());

        Addpnl.setBackground(new java.awt.Color(32, 47, 90));
        Addpnl.setLayout(null);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date Of Birth:");
        Addpnl.add(jLabel9);
        jLabel9.setBounds(10, 270, 77, 14);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Phone:");
        Addpnl.add(jLabel10);
        jLabel10.setBounds(10, 390, 50, 14);

        txtAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addpnl.add(txtAge);
        txtAge.setBounds(120, 340, 215, 30);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address:");
        Addpnl.add(jLabel11);
        jLabel11.setBounds(10, 430, 50, 14);

        txtPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addpnl.add(txtPhone);
        txtPhone.setBounds(120, 380, 215, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Balance:");
        Addpnl.add(jLabel7);
        jLabel7.setBounds(10, 470, 50, 14);

        txtAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        Addpnl.add(txtAddress);
        txtAddress.setBounds(120, 420, 215, 30);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Martial Status:");
        Addpnl.add(jLabel12);
        jLabel12.setBounds(10, 510, 77, 14);

        txtBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addpnl.add(txtBalance);
        txtBalance.setBounds(120, 460, 215, 30);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Gender:");
        Addpnl.add(jLabel13);
        jLabel13.setBounds(10, 550, 46, 14);

        txtMS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addpnl.add(txtMS);
        txtMS.setBounds(120, 500, 215, 30);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Emaill:");
        Addpnl.add(jLabel14);
        jLabel14.setBounds(10, 310, 77, 14);

        Male.setBackground(new java.awt.Color(0, 18, 50));
        buttonGroup1.add(Male);
        Male.setForeground(new java.awt.Color(255, 255, 255));
        Male.setText("Male");
        Addpnl.add(Male);
        Male.setBounds(120, 540, 70, 23);

        Female.setBackground(new java.awt.Color(0, 18, 50));
        buttonGroup1.add(Female);
        Female.setForeground(new java.awt.Color(255, 255, 255));
        Female.setText("Female");
        Addpnl.add(Female);
        Female.setBounds(250, 540, 80, 23);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Age:");
        Addpnl.add(jLabel15);
        jLabel15.setBounds(10, 350, 49, 14);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Father Name:");
        Addpnl.add(jLabel16);
        jLabel16.setBounds(10, 150, 70, 14);

        txtAC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addpnl.add(txtAC);
        txtAC.setBounds(120, 220, 215, 30);

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Mother Name:");
        Addpnl.add(jLabel17);
        jLabel17.setBounds(10, 190, 70, 14);

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Account Number:");
        Addpnl.add(jLabel18);
        jLabel18.setBounds(10, 230, 90, 14);

        jButton2.setBackground(new java.awt.Color(0, 18, 50));
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\+-.png")); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Addpnl.add(jButton2);
        jButton2.setBounds(150, 630, 149, 30);

        jButton4.setBackground(new java.awt.Color(0, 18, 50));
        jButton4.setForeground(new java.awt.Color(0, 102, 204));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\Add User Male_20px.png")); // NOI18N
        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Addpnl.add(jButton4);
        jButton4.setBounds(150, 590, 149, 30);

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\Shutdown_42px.png")); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        Addpnl.add(jLabel19);
        jLabel19.setBounds(0, 0, 44, 42);

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Name:");
        Addpnl.add(jLabel20);
        jLabel20.setBounds(10, 70, 64, 14);

        txtID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addpnl.add(txtID);
        txtID.setBounds(120, 100, 215, 30);

        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        Addpnl.add(jLabel22);
        jLabel22.setBounds(530, 0, 44, 0);

        DOB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addpnl.add(DOB);
        DOB.setBounds(120, 260, 215, 30);

        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        Addpnl.add(txtEmail);
        txtEmail.setBounds(120, 300, 215, 30);

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("ID:");
        Addpnl.add(jLabel8);
        jLabel8.setBounds(10, 110, 15, 14);

        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });
        Addpnl.add(txtName);
        txtName.setBounds(120, 60, 215, 30);

        jLabel41.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\AppData\\Local\\Temp\\Close Window_48px.png")); // NOI18N
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });
        Addpnl.add(jLabel41);
        jLabel41.setBounds(520, 0, 50, 40);

        txtFN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addpnl.add(txtFN);
        txtFN.setBounds(120, 140, 215, 30);

        txtMN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Addpnl.add(txtMN);
        txtMN.setBounds(120, 180, 215, 30);

        lbName.setForeground(new java.awt.Color(255, 255, 255));
        Addpnl.add(lbName);
        lbName.setBounds(430, 110, 140, 30);

        jButton6.setBackground(new java.awt.Color(0, 18, 50));
        jButton6.setForeground(new java.awt.Color(244, 244, 244));
        jButton6.setText("Insert Customer's Picture");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Addpnl.add(jButton6);
        jButton6.setBounds(360, 540, 180, 23);
        Addpnl.add(jLabel61);
        jLabel61.setBounds(360, 320, 180, 180);
        Addpnl.add(txtpic);
        txtpic.setBounds(360, 510, 180, 20);

        jPanel3.add(Addpnl, "card2");

        Modifypnl.setBackground(new java.awt.Color(32, 47, 90));
        Modifypnl.setLayout(null);

        MAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(MAge);
        MAge.setBounds(160, 380, 220, 30);

        Searchbtn.setBackground(new java.awt.Color(0, 18, 50));
        Searchbtn.setForeground(new java.awt.Color(0, 102, 204));
        Searchbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\AppData\\Local\\Temp\\Search_20px_1.png")); // NOI18N
        Searchbtn.setText("Serach");
        Searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbtnActionPerformed(evt);
            }
        });
        Modifypnl.add(Searchbtn);
        Searchbtn.setBounds(220, 57, 99, 29);

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Address:");
        Modifypnl.add(jLabel21);
        jLabel21.setBounds(10, 470, 60, 14);

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\Shutdown_42px.png")); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        Modifypnl.add(jLabel23);
        jLabel23.setBounds(10, 0, 44, 42);

        Mphone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(Mphone);
        Mphone.setBounds(160, 420, 220, 30);

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Balance:");
        Modifypnl.add(jLabel24);
        jLabel24.setBounds(10, 510, 60, 14);

        MAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(MAddress);
        MAddress.setBounds(160, 460, 220, 30);

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Name:");
        Modifypnl.add(jLabel25);
        jLabel25.setBounds(10, 110, 70, 14);

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Martial Status:");
        Modifypnl.add(jLabel26);
        jLabel26.setBounds(10, 550, 80, 14);

        MID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(MID);
        MID.setBounds(160, 140, 220, 30);

        MBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(MBalance);
        MBalance.setBounds(160, 500, 220, 30);

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Gender:");
        Modifypnl.add(jLabel27);
        jLabel27.setBounds(10, 590, 50, 14);

        MMS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMSActionPerformed(evt);
            }
        });
        Modifypnl.add(MMS);
        MMS.setBounds(160, 540, 220, 30);

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Account Number:");
        Modifypnl.add(jLabel28);
        jLabel28.setBounds(10, 310, 90, 14);

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Age:");
        Modifypnl.add(jLabel29);
        jLabel29.setBounds(10, 390, 50, 14);

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Father Name:");
        Modifypnl.add(jLabel30);
        jLabel30.setBounds(10, 190, 70, 14);

        MMN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(MMN);
        MMN.setBounds(160, 220, 220, 30);

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Mother Name:");
        Modifypnl.add(jLabel31);
        jLabel31.setBounds(10, 230, 70, 14);

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("ID:");
        Modifypnl.add(jLabel32);
        jLabel32.setBounds(10, 150, 80, 14);

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Date Of Birth:");
        Modifypnl.add(jLabel33);
        jLabel33.setBounds(10, 270, 80, 14);

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Phone:");
        Modifypnl.add(jLabel36);
        jLabel36.setBounds(10, 430, 60, 14);

        txtSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearch.setBorder(null);
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        Modifypnl.add(txtSearch);
        txtSearch.setBounds(10, 60, 200, 20);

        btnUpdate.setBackground(new java.awt.Color(0, 18, 50));
        btnUpdate.setForeground(new java.awt.Color(0, 204, 51));
        btnUpdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\AppData\\Local\\Temp\\Checked_20px_1.png")); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        Modifypnl.add(btnUpdate);
        btnUpdate.setBounds(210, 620, 110, 29);

        btnDelete.setBackground(new java.awt.Color(0, 18, 50));
        btnDelete.setForeground(new java.awt.Color(255, 0, 0));
        btnDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\AppData\\Local\\Temp\\Cancel_20px_1.png")); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        Modifypnl.add(btnDelete);
        btnDelete.setBounds(210, 660, 110, 29);

        MDOB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(MDOB);
        MDOB.setBounds(160, 260, 220, 30);

        MAC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(MAC);
        MAC.setBounds(160, 300, 220, 30);

        txtGender.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(txtGender);
        txtGender.setBounds(160, 580, 220, 30);

        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });
        Modifypnl.add(jLabel37);
        jLabel37.setBounds(490, 0, 44, 0);

        MFN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(MFN);
        MFN.setBounds(160, 180, 220, 30);

        MName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Modifypnl.add(MName);
        MName.setBounds(160, 100, 220, 30);

        jLabel42.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\AppData\\Local\\Temp\\Close Window_48px.png")); // NOI18N
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel42MouseClicked(evt);
            }
        });
        Modifypnl.add(jLabel42);
        jLabel42.setBounds(520, 0, 50, 40);

        MEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MEmailKeyReleased(evt);
            }
        });
        Modifypnl.add(MEmail);
        MEmail.setBounds(160, 340, 220, 30);

        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Emaill:");
        Modifypnl.add(jLabel44);
        jLabel44.setBounds(10, 350, 77, 14);

        jPanel3.add(Modifypnl, "card2");

        Listpnl.setBackground(new java.awt.Color(32, 47, 90));

        jLabel38.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\Shutdown_42px.png")); // NOI18N
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });

        jLabel43.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\AppData\\Local\\Temp\\Close Window_48px.png")); // NOI18N
        jLabel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel43MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Father's Name", "Mother's Name", "Account Number", "Date Of Birth", "Email", "Age", "Phone", "Address", "Balance", "Marital Status", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout ListpnlLayout = new javax.swing.GroupLayout(Listpnl);
        Listpnl.setLayout(ListpnlLayout);
        ListpnlLayout.setHorizontalGroup(
            ListpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListpnlLayout.createSequentialGroup()
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 480, Short.MAX_VALUE)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addContainerGap())
        );
        ListpnlLayout.setVerticalGroup(
            ListpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListpnlLayout.createSequentialGroup()
                .addGroup(ListpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel38)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        jPanel3.add(Listpnl, "card2");

        Transactionpnl.setBackground(new java.awt.Color(32, 47, 90));
        Transactionpnl.setToolTipText("");
        Transactionpnl.setLayout(null);

        jLabel34.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\Shutdown_42px.png")); // NOI18N
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        Transactionpnl.add(jLabel34);
        jLabel34.setBounds(0, 0, 44, 42);

        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });
        Transactionpnl.add(jLabel35);
        jLabel35.setBounds(530, 0, 44, 0);

        Exit.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\AppData\\Local\\Temp\\Close Window_48px.png")); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        Transactionpnl.add(Exit);
        Exit.setBounds(520, 0, 50, 40);

        txtMACN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Transactionpnl.add(txtMACN);
        txtMACN.setBounds(250, 410, 220, 30);

        h.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Transactionpnl.add(h);
        h.setBounds(170, 120, 220, 30);

        txtbalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Transactionpnl.add(txtbalance);
        txtbalance.setBounds(250, 250, 220, 30);

        txtM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Transactionpnl.add(txtM);
        txtM.setBounds(250, 370, 220, 30);

        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Insert Account Number to transfeer money:");
        Transactionpnl.add(jLabel45);
        jLabel45.setBounds(20, 420, 220, 20);

        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Insert Account  Number:");
        Transactionpnl.add(jLabel46);
        jLabel46.setBounds(10, 130, 120, 14);

        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Balance:");
        Transactionpnl.add(jLabel47);
        jLabel47.setBounds(20, 260, 60, 14);

        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Money needed:");
        Transactionpnl.add(jLabel48);
        jLabel48.setBounds(20, 380, 80, 14);

        Withdraw.setBackground(new java.awt.Color(0, 18, 50));
        buttonGroup2.add(Withdraw);
        Withdraw.setForeground(new java.awt.Color(244, 244, 244));
        Withdraw.setText("Withdraw");
        Transactionpnl.add(Withdraw);
        Withdraw.setBounds(80, 560, 90, 23);

        Deposite.setBackground(new java.awt.Color(0, 18, 50));
        buttonGroup2.add(Deposite);
        Deposite.setForeground(new java.awt.Color(244, 244, 244));
        Deposite.setText("Deposite");
        Deposite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositeActionPerformed(evt);
            }
        });
        Transactionpnl.add(Deposite);
        Deposite.setBounds(250, 560, 80, 23);

        Transfeermoney.setBackground(new java.awt.Color(0, 18, 50));
        buttonGroup2.add(Transfeermoney);
        Transfeermoney.setForeground(new java.awt.Color(244, 244, 244));
        Transfeermoney.setText("Transfer Money");
        Transfeermoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransfeermoneyActionPerformed(evt);
            }
        });
        Transactionpnl.add(Transfeermoney);
        Transfeermoney.setBounds(420, 560, 110, 23);

        jButton5.setBackground(new java.awt.Color(0, 18, 50));
        jButton5.setForeground(new java.awt.Color(51, 255, 51));
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\Ok_20px.png")); // NOI18N
        jButton5.setText("Done");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Transactionpnl.add(jButton5);
        jButton5.setBounds(140, 620, 100, 30);

        btnSeacrh2.setBackground(new java.awt.Color(0, 18, 50));
        btnSeacrh2.setForeground(new java.awt.Color(244, 244, 244));
        btnSeacrh2.setText("Search");
        btnSeacrh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeacrh2ActionPerformed(evt);
            }
        });
        Transactionpnl.add(btnSeacrh2);
        btnSeacrh2.setBounds(410, 120, 73, 23);

        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Date:");
        Transactionpnl.add(jLabel50);
        jLabel50.setBounds(20, 180, 110, 14);

        txtDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        Transactionpnl.add(txtDate);
        txtDate.setBounds(250, 170, 220, 30);

        txtCName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNameActionPerformed(evt);
            }
        });
        Transactionpnl.add(txtCName);
        txtCName.setBounds(250, 210, 220, 30);

        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Customer Name:");
        Transactionpnl.add(jLabel51);
        jLabel51.setBounds(20, 220, 110, 14);

        txtTN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTNActionPerformed(evt);
            }
        });
        Transactionpnl.add(txtTN);
        txtTN.setBounds(250, 330, 220, 30);

        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Transaction Number:");
        Transactionpnl.add(jLabel54);
        jLabel54.setBounds(20, 340, 100, 14);

        yassen.setForeground(new java.awt.Color(32, 47, 90));
        yassen.setText("jLabel55");
        Transactionpnl.add(yassen);
        yassen.setBounds(510, 690, 40, 30);

        txtcc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Transactionpnl.add(txtcc);
        txtcc.setBounds(250, 450, 220, 30);

        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("cc:");
        Transactionpnl.add(jLabel58);
        jLabel58.setBounds(20, 460, 70, 14);

        txtsub.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Transactionpnl.add(txtsub);
        txtsub.setBounds(250, 490, 220, 30);

        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Subject:");
        Transactionpnl.add(jLabel59);
        jLabel59.setBounds(20, 500, 70, 14);

        txtemail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Transactionpnl.add(txtemail);
        txtemail.setBounds(250, 290, 220, 30);

        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Email:");
        Transactionpnl.add(jLabel60);
        jLabel60.setBounds(20, 300, 60, 14);

        txtCBS.setBackground(new java.awt.Color(0, 18, 50));
        txtCBS.setForeground(new java.awt.Color(244, 244, 244));
        txtCBS.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\Bill_20px.png")); // NOI18N
        txtCBS.setText("Create Balance Sheet");
        txtCBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCBSActionPerformed(evt);
            }
        });
        Transactionpnl.add(txtCBS);
        txtCBS.setBounds(310, 620, 150, 30);

        txtb.setForeground(new java.awt.Color(32, 47, 90));
        Transactionpnl.add(txtb);
        txtb.setBounds(50, 700, 40, 50);

        txtReset.setBackground(new java.awt.Color(0, 18, 50));
        txtReset.setForeground(new java.awt.Color(255, 0, 0));
        txtReset.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\Cancel_20px_2.png")); // NOI18N
        txtReset.setText("Reset");
        txtReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResetActionPerformed(evt);
            }
        });
        Transactionpnl.add(txtReset);
        txtReset.setBounds(240, 660, 90, 30);

        jPanel3.add(Transactionpnl, "card5");

        Reportpnl.setBackground(new java.awt.Color(32, 47, 90));
        Reportpnl.setLayout(null);

        jButton3.setText("jButton3");
        Reportpnl.add(jButton3);
        jButton3.setBounds(250, 230, 73, 23);

        jLabel39.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\Shutdown_42px.png")); // NOI18N
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel39MouseClicked(evt);
            }
        });
        Reportpnl.add(jLabel39);
        jLabel39.setBounds(0, 0, 44, 42);

        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });
        Reportpnl.add(jLabel40);
        jLabel40.setBounds(530, 0, 44, 0);

        jPanel3.add(Reportpnl, "card6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 790);

        CBSpnl.setBackground(new java.awt.Color(32, 47, 90));
        CBSpnl.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(0, 18, 50));
        jButton1.setForeground(new java.awt.Color(244, 244, 244));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\Bill_20px.png")); // NOI18N
        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtFB.setBackground(new java.awt.Color(0, 102, 204));
        txtFB.setForeground(new java.awt.Color(255, 255, 255));

        txtW.setBackground(new java.awt.Color(0, 102, 204));
        txtW.setForeground(new java.awt.Color(255, 255, 255));

        txtD.setBackground(new java.awt.Color(0, 102, 204));
        txtD.setForeground(new java.awt.Color(255, 255, 255));

        txtT.setBackground(new java.awt.Color(0, 102, 204));
        txtT.setForeground(new java.awt.Color(255, 255, 255));

        txtFinalB.setBackground(new java.awt.Color(0, 102, 204));
        txtFinalB.setForeground(new java.awt.Color(255, 255, 255));

        txtac.setBackground(new java.awt.Color(0, 102, 204));
        txtac.setForeground(new java.awt.Color(255, 255, 255));

        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Your Account Number:");

        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Your First Balance was: ");

        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("You Made Withdraw :");

        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("You Made Deposite:");

        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("You Made Transfeer:");

        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Your Final Balance:");

        jLabel62.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\Close Window_42px.png")); // NOI18N
        jLabel62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel62MouseClicked(evt);
            }
        });

        jLabel63.setIcon(new javax.swing.ImageIcon("C:\\Users\\y_awn\\Desktop\\Pl2 Photo\\Shutdown_42px.png")); // NOI18N
        jLabel63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel63MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CBSpnlLayout = new javax.swing.GroupLayout(CBSpnl);
        CBSpnl.setLayout(CBSpnlLayout);
        CBSpnlLayout.setHorizontalGroup(
            CBSpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CBSpnlLayout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addGroup(CBSpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49)
                    .addComponent(jLabel52)
                    .addComponent(jLabel53)
                    .addComponent(jLabel55)
                    .addComponent(jLabel56)
                    .addComponent(jLabel57))
                .addGap(88, 88, 88)
                .addGroup(CBSpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtFinalB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtW, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtac, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CBSpnlLayout.createSequentialGroup()
                .addComponent(jLabel63)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(CBSpnlLayout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CBSpnlLayout.setVerticalGroup(
            CBSpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CBSpnlLayout.createSequentialGroup()
                .addGroup(CBSpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(CBSpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CBSpnlLayout.createSequentialGroup()
                        .addGroup(CBSpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(CBSpnlLayout.createSequentialGroup()
                                .addGroup(CBSpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(CBSpnlLayout.createSequentialGroup()
                                        .addGroup(CBSpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(CBSpnlLayout.createSequentialGroup()
                                                .addGroup(CBSpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(CBSpnlLayout.createSequentialGroup()
                                                        .addGroup(CBSpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(txtac, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel49))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txtFB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel52))
                                                .addGap(18, 18, 18)
                                                .addComponent(txtW, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel53))
                                        .addGap(18, 18, 18)
                                        .addComponent(txtD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel55))
                                .addGap(18, 18, 18)
                                .addComponent(txtT, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel56))
                        .addGap(18, 18, 18)
                        .addComponent(txtFinalB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel57))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        getContentPane().add(CBSpnl);
        CBSpnl.setBounds(0, 0, 686, 553);

        setSize(new java.awt.Dimension(769, 709));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void addRowsTojTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object rowData[] = new Object[13];

        Customer c = new Customer();
        ArrayList<Customer> customer = new ArrayList<Customer>();

        customer = c.listCustomer();
                    
        for (Customer x : customer) {
            rowData[0] = x.getName();
            rowData[1] = x.getId();
            rowData[2] = x.getFatherName();
            rowData[3] = x.getMotherName();
            rowData[4] = x.getaccountnumber();
            rowData[5] = x.getDateOfBirth();
            rowData[6] = x.getemail();
            rowData[7] = x.getage();
            rowData[8] = x.getphone();
            rowData[9] = x.getaddress();
            rowData[10] = x.getbalance();
            rowData[11] = x.getmaritalstatus();
            rowData[12] = x.getGender();
            
            model.addRow(rowData);
        }     
    }
    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Addpnl);
        jPanel3.repaint();
        jPanel3.revalidate();

    }//GEN-LAST:event_AddbtnActionPerformed

    private void ModifybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifybtnActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Modifypnl);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_ModifybtnActionPerformed

    private void ListbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListbtnActionPerformed
        // TODO add your handling code here:
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Listpnl);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_ListbtnActionPerformed
public void ResetA(){
       txtAC.setText("");
        txtMN.setText("");
        txtFN.setText("");
        txtAC.setText("");
        txtName.setText("");
        txtID.setText("");
        DOB.setText("");
        txtEmail.setText("");
        txtAge.setText("");
        txtPhone.setText("");
        txtAddress.setText("");
        txtBalance.setText("");
        txtMS.setText("");
        buttonGroup1.clearSelection();
        txtpic.setText("");
        jLabel61.setText("");
 
 }
public void ResetT(){
h.setText("");
txtDate.setText("");
txtCName.setText("");
txtbalance.setText("");
txtemail.setText("");
txtTN.setText("");
txtM.setText("");
txtMACN.setText("");
txtcc.setText("");
txtsub.setText("");
buttonGroup2.clearSelection();
}
 public void ResetM(){
       MName.setText("");
       MID.setText("");
        MMN.setText("");
        MFN.setText("");
        MDOB.setText("");
        MAC.setText("");
        MAge.setText("");
        Mphone.setText("");
        MAddress.setText("");
        MBalance.setText("");
        MMS.setText("");
        txtGender.setText("");
        MEmail.setText("");
 }
    private void TransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionsActionPerformed
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(Transactionpnl);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_TransactionsActionPerformed

    private void Listbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listbtn2ActionPerformed
     Transactions T=new Transactions();
  ArrayList<Transactions> v =new ArrayList<Transactions>();
   v=T.listTransaction();
  String[] tdate=new String[v.size()];
 double[] tmoney=new double[v.size()];
 for(int i=0;i<v.size();i++){
     
     tdate[i]=v.get(i).getDate();
     tmoney[i]=v.get(i).getMoney();
     System.out.println(tdate[i]);
     System.out.println(tmoney[i]);
      
 }
        BarChart Chart=new BarChart("Transactions Report",tdate,tmoney);
        Chart.pack();
        RefineryUtilities.centerFrameOnScreen(Chart);
        Chart.setVisible(true);
       
     
       
    }//GEN-LAST:event_Listbtn2ActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ResetA();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try{
            
            if(!txtpic.getText().equals("")){
        Customer x=new Customer();
        x.LoadFromFile();
        int id= Integer.parseInt(txtID.getText());
        int index= x.getCustomerIndex(id);
       
        if(index==-1){
                       

            String gender = null;
            if(Male.isSelected()){
                gender="Male";
            }
            else if(Female.isSelected()){
                gender="Female";
            }
            int i=0;
        int k;
      ExClass n=new ExClass();
      k=n.ValidateEmail(txtEmail.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Email in not validated");}
      k=n.ValidateNumber(txtAC.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Account Number in not validated");}
      k=n.ValidtaeName(txtName.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Name in not validated");}
      k=n.ValidateNumber(txtID.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "ID in not validated");}
     
      k=n.ValidateNumber(txtAge.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Age in not validated");}
      k=n.ValidateNumber(txtPhone.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Phone in not validated");}
      k=n.ValidateNumber(txtBalance.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Balance in not validated");}
      k=n.ValidtaeName(txtFN.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Father Name in not validated");}
      k=n.ValidtaeName(txtMN.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Mother Name in not validated");}
        
      if(i==9){

            Employee emp = new Employee();
      emp.addNewCustomer(txtName.getText(),Integer.parseInt(txtID.getText()) ,txtFN.getText(), txtMN.getText(),Integer.parseInt(txtAC.getText()), DOB.getText(),txtEmail.getText(),Integer.parseInt(txtAge.getText()),Long.parseLong(txtPhone.getText()),txtAddress.getText(),Double.parseDouble(txtBalance.getText()),txtMS.getText() , gender,txtpic.getText());
            JOptionPane.showMessageDialog(null,"Done!!");
            ResetA();
        
       
        }
        else{
            JOptionPane.showMessageDialog(null," Please insert coreect data");}
       }else{
                JOptionPane.showMessageDialog(null,"The Customer Is Already Exist");
                }}
            else{
            JOptionPane.showMessageDialog(null,"please insert the photo!!");
            }}
       
       catch(Exception e){
       JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to logout?","Logout",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            dispose();
            Loginfrm l=new Loginfrm();
            l.setVisible(true);
        }

    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to Exit?","Exit",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }

    }//GEN-LAST:event_jLabel22MouseClicked

    private void SearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbtnActionPerformed
        if (!txtSearch.getText().equals("")) {
            
            Customer x = new Customer();
            x.LoadFromFile();
            int id= Integer.parseInt(txtSearch.getText());
            int index= x.getCustomerIndex(id);
            if(index!=-1){
                MName.setText(customer.get(index).getName());
                MID.setText(String.valueOf(customer.get(index).getId()));
                MFN.setText(customer.get(index).getFatherName());
                MMN.setText(customer.get(index).getMotherName());
                MDOB.setText(customer.get(index).getDateOfBirth());
                MAC.setText(String.valueOf(customer.get(index).getaccountnumber()));
                MEmail.setText(customer.get(index).getemail());
                MAge.setText(String.valueOf(customer.get(index).getage()));
                Mphone.setText(String.valueOf(customer.get(index).getphone()));
                MAddress.setText(customer.get(index).getaddress());
                MBalance.setText(String.valueOf(customer.get(index).getbalance()));
                MMS.setText(customer.get(index).getmaritalstatus());
                txtGender.setText(customer.get(index).getGender());

            }

            else {
                JOptionPane.showMessageDialog(null, "Not Found ...!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Missing required Fields ... !  Please, Search By ID before submit ...!");
        }

    }//GEN-LAST:event_SearchbtnActionPerformed

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to logout?","Logout",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            dispose();
            Loginfrm l=new Loginfrm();
            l.setVisible(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23MouseClicked

    private void MMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MMSActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
 int i=0;
        int k;
      ExClass n=new ExClass();
      k=n.ValidateEmail(MEmail.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Email in not validated");}
      k=n.ValidateNumber(MAC.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Account Number in not validated");}
      k=n.ValidtaeName(MName.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Name in not validated");}
      k=n.ValidateNumber(MID.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "ID in not validated");}
     
      k=n.ValidateNumber(MAge.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Age in not validated");}
      k=n.ValidateNumber(Mphone.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Phone in not validated");}
      k=n.ValidateNumber(MBalance.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Balance in not validated");}
      k=n.ValidtaeName(MFN.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Father Name in not validated");}
      k=n.ValidtaeName(MMN.getText());
      if(k==1){
      i++;
      }
      else {JOptionPane.showMessageDialog(null, "Mother Name in not validated");}
        if(i==9){
        Customer x= new Customer();
        x.SetName(MName.getText());
        x.SetId(Integer.parseInt(MID.getText()));
        x.SetFatherName(MFN.getText());
        x.SetMotherName(MMN.getText());
        x.SetDateOfBirth(MDOB.getText());
        x.Setaccountnumber(Integer.parseInt(MAC.getText()));
        x.Setemail(MEmail.getText());
        x.SetAge(Integer.parseInt(MAge.getText()));
        x.SetPhone(Long.parseLong(Mphone.getText()));
        x.SetAddress(MAddress.getText());
        x.Setbalance(Double.parseDouble(MBalance.getText()));
        x.Setmaritalstatus(MMS.getText());
        x.SetGender(txtGender.getText());
        if(x.updateCustomer()){
            JOptionPane.showMessageDialog(null, "Updated Successfully....!!!!");
            ResetM();
            txtSearch.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null, "Faild To Update!!!");
        }}
        else{
        JOptionPane.showMessageDialog(null,"please insert correct data");
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (!txtSearch.getText().equals("")) {
            Customer e=new Customer();
            if(e.deleteCustomer(Integer.parseInt(txtSearch.getText()))){
                JOptionPane.showMessageDialog(null, "Deleted Done!!");
                ResetM();
                txtSearch.setText("");
            }
            else{
                JOptionPane.showMessageDialog(null,"Failed to Delete");
            }

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to Exit?","Exit",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel37MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        // TODO add your handling code here:
        int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to logout?","Logout",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            dispose();
            Loginfrm l=new Loginfrm();
            l.setVisible(true);
        }

    }//GEN-LAST:event_jLabel38MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to logout?","Logout",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            dispose();
            Loginfrm l=new Loginfrm();
            l.setVisible(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to Exit?","Exit",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseClicked
int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to logout?","Logout",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            dispose();
            Loginfrm l=new Loginfrm();
            l.setVisible(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel39MouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to Exit?","Exit",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel40MouseClicked

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to Exit?","Exit",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel41MouseClicked

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
       
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
      // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
   // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
       
    }//GEN-LAST:event_txtEmailKeyReleased

    private void jLabel42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseClicked
int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to Exit?","Exit",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel42MouseClicked

    private void jLabel43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseClicked
int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to Exit?","Exit",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel43MouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to Exit?","Exit",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_ExitMouseClicked

    private void MEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MEmailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_MEmailKeyReleased

    private void TransfeermoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransfeermoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TransfeermoneyActionPerformed

    private void btnSeacrh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeacrh2ActionPerformed
if (!h.getText().equals("")) {
            
            Customer x = new Customer();
            x.LoadFromFile();
            int AccountNumber= Integer.parseInt(h.getText());
            int index= x.getCustomerIndex2(AccountNumber);
            if(index!=-1){
               txtbalance.setText(String.valueOf(customer.get(index).getbalance()));
               yassen.setText(String.valueOf(index));
               txtCName.setText(customer.get(index).getName());
               txtemail.setText(customer.get(index).getemail());
            }

            else {
                JOptionPane.showMessageDialog(null, "Not Found ...!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Missing required Fields ... !  Please, Search By ID before submit ...!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeacrh2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     Customer x=new Customer();
     Employee e=new Employee();
     String kind="";
     int k=0;
     try{
     if(Withdraw.isSelected()){
       double b=Double.parseDouble(txtbalance.getText());
       double s=Double.parseDouble(txtM.getText());
        kind="withdraw";
       if(b>=s){
        double result =b-s;
       int index=Integer.parseInt(yassen.getText());
       customer.get(index).Setbalance(result);
      
       JOptionPane.showMessageDialog(null,"Withdraw operation done!!");
       k++;
       
       e.addnewTransaction(txtDate.getText(),Integer.parseInt(h.getText()), Double.parseDouble(txtbalance.getText()),Integer.parseInt(txtTN.getText()),Double.parseDouble(txtM.getText()), kind,Integer.parseInt(h.getText()));
        x.committofile();
       }
        else{
        JOptionPane.showMessageDialog(null, "your balnce is not enough");
        }
       }
       else if(Deposite.isSelected()){
       
        kind="Deposite";
       double b=Double.parseDouble(txtbalance.getText());
       double s=Double.parseDouble(txtM.getText());
        double result =b+s;
       int index=Integer.parseInt(yassen.getText());
       customer.get(index).Setbalance(result);
       x.committofile();
       JOptionPane.showMessageDialog(null,"deposite operation done!!");
       k++;
       e.addnewTransaction(txtDate.getText(),Integer.parseInt(h.getText()), Double.parseDouble(txtbalance.getText()),Integer.parseInt(txtTN.getText()),Double.parseDouble(txtM.getText()), kind,Integer.parseInt(h.getText()));
       }
       
       
       
       
       
       else if(Transfeermoney.isSelected()){
        kind="Transfer money";
       double b=Double.parseDouble(txtbalance.getText());
       double s=Double.parseDouble(txtM.getText()); 
       double m;
       int AC=Integer.parseInt(txtMACN.getText());
       int index=x.getCustomerIndex2(AC);
       if(index!=-1){
       m=customer.get(index).getbalance();
       if(b>=s){
       double r1=b-s;
       double r2=m+s;
       customer.get(index).Setbalance(r2);
       customer.get(Integer.parseInt(yassen.getText())).Setbalance(r1);
       x.committofile();
       JOptionPane.showMessageDialog(null,"Done!!");
       k++;
       e.addnewTransaction(txtDate.getText(),Integer.parseInt(h.getText()), Double.parseDouble(txtbalance.getText()),Integer.parseInt(txtTN.getText()),Double.parseDouble(txtM.getText()), kind,Integer.parseInt(txtMACN.getText()));

     
       }
       else{
       JOptionPane.showMessageDialog(null,"the balance is not enough!!");
       }
       
       }
       else{JOptionPane.showMessageDialog(null,"the second customer is not found!!");}
       
    
       }
     int l=0;
        double a,s,d;
     if(Withdraw.isSelected()){
 
        l=1;
        }
        else if(Deposite.isSelected()){
        
        l=2;
        }
        else if(Transfeermoney.isSelected()){
        
        l=3;
        }
        if(l==1){
         s=Double.parseDouble(txtM.getText());
         a=Double.parseDouble(txtbalance.getText());
         d=a-s;
         txtb.setText(String.valueOf(d));
        }
        else if(l==2){
        s=Double.parseDouble(txtM.getText());
         a=Double.parseDouble(txtbalance.getText());
         d=a+s;
         txtb.setText(String.valueOf(d));
        }
        else if(l==3){
        s=Double.parseDouble(txtM.getText());
         a=Double.parseDouble(txtbalance.getText());
         d=a-s;
         txtb.setText(String.valueOf(d));
        }
     //@Email@
    if(k==1){
         String Kareem="hello "+txtCName.getText()+"<br>"+"Your Account Number is: "+h.getText()+"<br>"+"your balance was: "+txtbalance.getText()+"<br>"+"the transaction number is: "+txtTN.getText()+"<br>"+"the amount of money is: "+txtM.getText()+"<br>"+"the teransaction kind is: "+txtsub.getText()+"<br>"+"your balance is: "+txtb.getText();

     try {
                Email email = new Email(txtemail.getText(), txtcc.getText(),txtsub.getText(), Kareem);
                email.generateAndSendEmail();
                JOptionPane.showMessageDialog(null, "Your message has been delivered.");
                

            } catch (MessagingException ex) {
                JOptionPane.showMessageDialog(null, "Your message hasn't been delivered.");
                Logger.getLogger(Employeefrm.class.getName()).log(Level.SEVERE, null, ex);
            }
     }
     }
     catch(Exception ex){
     JOptionPane.showMessageDialog(null,ex);
     }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void DepositeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositeActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_DepositeActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtCNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNameActionPerformed

    private void txtTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    /*txtac.setText(h.getText());
        Transactions x=new Transactions();
    int AC=Integer.parseInt(txtac.getText());
    x.LoadFromFile();
    int[] index=x.getCustomerIndex3(AC);
    if(index==null){
     JOptionPane.showMessageDialog(null,"Customer Not Found!!!");
    }
        
        else {
       
        double []deposite=null;
    double []withdraw = null;
    double []transfeer=null;
    JOptionPane.showMessageDialog(null,"3");
    int i;
    int k=0;
    for(i=0;i<=index.length;i++){
        JOptionPane.showMessageDialog(null,"4");
    if(transactions.get(index[i]).getTransactionKind().equals("withdraw")){
    withdraw[k] =transactions.get(index[i]).getMoney();
    JOptionPane.showMessageDialog(null,"5");
    k++;
    }
   else if(transactions.get(index[i]).getTransactionKind().equals("Deposite")){
   deposite[k]=transactions.get(index[i]).getMoney();
   JOptionPane.showMessageDialog(null,"6");
   k++;
   }
    else if(transactions.get(index[i]).getTransactionKind().equals("Transfer money")){
    transfeer[k]=transactions.get(index[i]).getMoney();
    JOptionPane.showMessageDialog(null,"7");
    k++;
    }
    }
    double sumD=DoubleStream.of(deposite).sum();
    JOptionPane.showMessageDialog(null,"8");
    double sumW=DoubleStream.of(withdraw).sum();
    JOptionPane.showMessageDialog(null,"9");
    double sumT=DoubleStream.of(transfeer).sum();
    JOptionPane.showMessageDialog(null,"10");
    double Balance=transactions.get(index[0]).getBalance();
    JOptionPane.showMessageDialog(null,"11");
    double FinalBalance=Balance+sumD-sumW-sumT;
    JOptionPane.showMessageDialog(null,"12");
    txtFB.setText(String.valueOf(Balance));
    JOptionPane.showMessageDialog(null,"13");
    txtac.setText(h.getText());
    JOptionPane.showMessageDialog(null,"14");
    txtW.setText(String.valueOf(sumW));
    JOptionPane.showMessageDialog(null,"15");
    txtD.setText(String.valueOf(sumD));
    JOptionPane.showMessageDialog(null,"16");
    txtT.setText(String.valueOf(sumT));
    JOptionPane.showMessageDialog(null,"17");
    txtFinalB.setText(String.valueOf(FinalBalance));
    JOptionPane.showMessageDialog(null,"18");
        } */
        // TODO add your handling code here:
        txtac.setText(h.getText());
        txtFB.setText(txtbalance.getText());
        int k=0;
        double x,y,z;
        if(Withdraw.isSelected()){
        txtW.setText(txtM.getText());
        txtD.setText("0");
        txtT.setText("0");
        k=1;
        }
        else if(Deposite.isSelected()){
        txtW.setText("0");
        txtD.setText(txtM.getText());
        txtT.setText("0");
        k=2;
        }
        else if(Transfeermoney.isSelected()){
        txtW.setText("0");
        txtD.setText("0");
        txtT.setText(txtM.getText());
        k=3;
        }
        if(k==1){
         x=Double.parseDouble(txtW.getText());
         y=Double.parseDouble(txtbalance.getText());
         z=y-x;
         txtFinalB.setText(String.valueOf(z));
        }
        else if(k==2){
        x=Double.parseDouble(txtD.getText());
         y=Double.parseDouble(txtbalance.getText());
         z=y+x;
         txtFinalB.setText(String.valueOf(z));
        }
        else if(k==3){
        x=Double.parseDouble(txtW.getText());
         y=Double.parseDouble(txtbalance.getText());
         z=y-x;
         txtFinalB.setText(String.valueOf(z));
         
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCBSActionPerformed
jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(CBSpnl);
        jPanel3.repaint();
        jPanel3.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_txtCBSActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        String filename="Customer.png";
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        if (f.isFile()){
            filename = f.getAbsolutePath();
        }
        
        txtpic.setText(filename);
        try {
            ImageIcon icon =new ImageIcon(ImageIO.read(new File(filename)));
            jLabel61.setIcon(icon);
        } catch (IOException ex) {
            System.out.println(ex);
        }
            
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel62MouseClicked
        int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to Exit?","Exit",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        } // TODO add your handling code here:
    }//GEN-LAST:event_jLabel62MouseClicked

    private void jLabel63MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel63MouseClicked
int confirmed = JOptionPane.showConfirmDialog(null, "Are you sure You need to logout?","Logout",JOptionPane.YES_NO_OPTION);
        if(confirmed == JOptionPane.YES_OPTION)
        {
            dispose();
            Loginfrm l=new Loginfrm();
            l.setVisible(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel63MouseClicked

    private void txtResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResetActionPerformed
ResetT();        // TODO add your handling code here:
    }//GEN-LAST:event_txtResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employeefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employeefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employeefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employeefrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employeefrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JPanel Addpnl;
    private javax.swing.JPanel CBSpnl;
    private javax.swing.JTextField DOB;
    private javax.swing.JRadioButton Deposite;
    private javax.swing.JLabel Exit;
    private javax.swing.JRadioButton Female;
    private javax.swing.JButton Listbtn;
    private javax.swing.JButton Listbtn2;
    private javax.swing.JPanel Listpnl;
    private javax.swing.JTextField MAC;
    private javax.swing.JTextField MAddress;
    private javax.swing.JTextField MAge;
    private javax.swing.JTextField MBalance;
    private javax.swing.JTextField MDOB;
    private javax.swing.JTextField MEmail;
    private javax.swing.JTextField MFN;
    private javax.swing.JTextField MID;
    private javax.swing.JTextField MMN;
    private javax.swing.JTextField MMS;
    private javax.swing.JTextField MName;
    private javax.swing.JRadioButton Male;
    private javax.swing.JButton Modifybtn;
    private javax.swing.JPanel Modifypnl;
    private javax.swing.JTextField Mphone;
    private javax.swing.JPanel Reportpnl;
    private javax.swing.JButton Searchbtn;
    private javax.swing.JPanel Transactionpnl;
    private javax.swing.JButton Transactions;
    private javax.swing.JRadioButton Transfeermoney;
    private javax.swing.JRadioButton Withdraw;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSeacrh2;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField h;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbName;
    private javax.swing.JTextField txtAC;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JButton txtCBS;
    private javax.swing.JTextField txtCName;
    private javax.swing.JLabel txtD;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel txtFB;
    private javax.swing.JTextField txtFN;
    private javax.swing.JLabel txtFinalB;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtM;
    private javax.swing.JTextField txtMACN;
    private javax.swing.JTextField txtMN;
    private javax.swing.JTextField txtMS;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JButton txtReset;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLabel txtT;
    private javax.swing.JTextField txtTN;
    private javax.swing.JLabel txtW;
    private javax.swing.JLabel txtac;
    private javax.swing.JLabel txtb;
    private javax.swing.JTextField txtbalance;
    private javax.swing.JTextField txtcc;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtpic;
    private javax.swing.JTextField txtsub;
    private javax.swing.JLabel yassen;
    // End of variables declaration//GEN-END:variables
}
